# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1780892a19fe6846944db48a31a6e716"
name = "AI-GEO"
application_url = "https://ai-geo.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ai-geo.vercel.app/auth/callback",
  "https://ai-geo.vercel.app/auth/shopify/callback"
]
